[build]
  command = "yarn build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' *.cloudfront.net *.cloudinary.com *.google.com *.gstatic.com *.google-analytics.com *.googletagmanager.com; frame-ancestors 'self'; form-action 'self'"
