[build]
  command = "yarn build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self' cloudinary.com *.cloudinary.com; font-src 'self' gstatic.com *.gstatic.com; manifest-src 'self'; style-src 'unsafe-inline' cloudfront.net *.cloudfront.net; frame-ancestors 'self'; form-action 'self'; script-src-elem 'unsafe-inline' googletagmanager.com *.googletagmanager.com"
